# -------------------------------------------------------
# Copyright (c) [2022] Nadege Lemperiere
# All rights reserved
# -------------------------------------------------------
# Analysis pipeline for website
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 30 november 2023
# -------------------------------------------------------

name: Module Release Pipeline

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

    check:
        name: Build Module
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Linting code
              uses: docker://nadegelemperiere/terraform-python-awscli:v3.0.0
              with:
                args: ./scripts/lint.sh

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/iac@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@main
              if: always()
              with:
                sarif_file: snyk.sarif

    test:
        name: Testing Module
        runs-on: ubuntu-latest
        needs: [check]
        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                path: module

            - name: Retrieving vault
              uses: actions/checkout@master
              with:
                repository: nadegelemperiere-aws/vault
                path: vault
                ref: v1.0.0
                token: ${{ secrets.GH_ACCESS_TOKEN }}

            - name: Launching tests
              env:
                VAULT_KEY: ${{ secrets.VAULT_KEY }}
              uses: docker://nadegelemperiere/terraform-python-awscli:v3.0.0
              with:
                args: ./module/scripts/robot.sh -l WARN -d tests -k VAULT_KEY

            - name: Push test report to Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                publish_dir: ./tests
                github_token: ${{ secrets.GH_ACCESS_TOKEN }}
                commit_message: "Generate Test report"
